# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\tools\【李群】赋能起航二期审核工具\programs\IGP3.2 Report Checker.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QTableWidget, QHBoxLayout, QApplication, QTableWidgetItem, QAbstractItemView
import os

class Ui_MainWindow(object):
    def setupUi(self, Report_Checker):
        Report_Checker.setObjectName("Report_Checker")
        Report_Checker.resize(990, 740)
        self.centralwidget = QtWidgets.QWidget(Report_Checker)
        self.centralwidget.setObjectName("centralwidget")

        self.report_info_table = QtWidgets.QTableWidget(self.centralwidget)
        self.report_info_table.setGeometry(QtCore.QRect(20, 20, 691, 651))
        self.report_info_table.setObjectName("report_info_table")
        self.report_info_table.setColumnCount(7)
        self.report_info_table.setRowCount(0)
        self.report_info_table.setHorizontalHeaderLabels(['姓名', '编号', '报告', '提交日期', '下载情况', '审核结果', '审核状况/不合格原因'])
        self.report_info_table.setSelectionBehavior(QAbstractItemView.SelectRows)  # 设置表格整行选中

        # 定义路径
        workspace_path: str = os.path.dirname(os.path.realpath(__file__))

        # 设置列的宽度
        for k in range(0, 6):
            self.report_info_table.setColumnWidth(k, 75)
        self.report_info_table.setColumnWidth(6, 210)
        
        # 添加华医网和IGP的LOGO
        self.huayi_pic_lable = QtWidgets.QLabel(self.centralwidget)
        self.huayi_pic_lable.setGeometry(QtCore.QRect(770, 600, 151, 51))
        self.huayi_pic_lable.setText("")
        self.huayi_pic_lable.setPixmap(QtGui.QPixmap(os.path.join(workspace_path, "pics\\huayi_logo.png")))
        self.huayi_pic_lable.setScaledContents(True)
        self.huayi_pic_lable.setObjectName("huayi_pic_lable")
        self.igp_pic_label = QtWidgets.QLabel(self.centralwidget)
        self.igp_pic_label.setGeometry(QtCore.QRect(770, 20, 171, 51))
        self.igp_pic_label.setText("")
        self.igp_pic_label.setPixmap(QtGui.QPixmap(os.path.join(workspace_path, "pics\\igp3_logo.png")))
        self.igp_pic_label.setScaledContents(True)
        self.igp_pic_label.setObjectName("igp_pic_label")

        #设置窗口图标
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(workspace_path, "pics\\igp3_icon.ico")),QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Report_Checker.setWindowIcon(icon)

        self.get_date_gpbx = QtWidgets.QGroupBox(self.centralwidget)
        self.get_date_gpbx.setGeometry(QtCore.QRect(740, 80, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.get_date_gpbx.setFont(font)
        self.get_date_gpbx.setObjectName("get_date_gpbx")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.get_date_gpbx)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 211, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.load_report_list_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.load_report_list_btn.setObjectName("load_report_list_btn")
        self.horizontalLayout_3.addWidget(self.load_report_list_btn)
        self.clear_report_list_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.clear_report_list_btn.setObjectName("clear_report_list_btn")
        self.horizontalLayout_3.addWidget(self.clear_report_list_btn)
        self.open_folder_gpbx = QtWidgets.QGroupBox(self.centralwidget)
        self.open_folder_gpbx.setGeometry(QtCore.QRect(740, 480, 231, 111))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.open_folder_gpbx.setFont(font)
        self.open_folder_gpbx.setObjectName("open_folder_gpbx")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.open_folder_gpbx)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 211, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.original_folder_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.original_folder_btn.setObjectName("original_folder_btn")
        self.horizontalLayout_2.addWidget(self.original_folder_btn)
        self.passed_folder_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.passed_folder_btn.setObjectName("passed_folder_btn")
        self.horizontalLayout_2.addWidget(self.passed_folder_btn)
        self.open_ppt_btn = QtWidgets.QPushButton(self.open_folder_gpbx)
        self.open_ppt_btn.setGeometry(QtCore.QRect(10, 70, 211, 25))
        self.open_ppt_btn.setObjectName("open_ppt_btn")
        self.download_gpbx = QtWidgets.QGroupBox(self.centralwidget)
        self.download_gpbx.setGeometry(QtCore.QRect(740, 170, 231, 111))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.download_gpbx.setFont(font)
        self.download_gpbx.setObjectName("download_gpbx")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.download_gpbx)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 211, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.download_selected_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.download_selected_btn.setObjectName("download_selected_btn")
        self.horizontalLayout_5.addWidget(self.download_selected_btn)
        self.dwonload_page_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.dwonload_page_btn.setObjectName("dwonload_page_btn")
        self.horizontalLayout_5.addWidget(self.dwonload_page_btn)
        self.download_all_btn = QtWidgets.QPushButton(self.download_gpbx)
        self.download_all_btn.setGeometry(QtCore.QRect(10, 70, 211, 25))
        self.download_all_btn.setObjectName("download_all_btn")
        self.change_page_gpbx = QtWidgets.QGroupBox(self.centralwidget)
        self.change_page_gpbx.setGeometry(QtCore.QRect(740, 390, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.change_page_gpbx.setFont(font)
        self.change_page_gpbx.setObjectName("change_page_gpbx")
        self.pgup_btn = QtWidgets.QPushButton(self.change_page_gpbx)
        self.pgup_btn.setGeometry(QtCore.QRect(10, 30, 71, 25))
        self.pgup_btn.setObjectName("pgup_btn")
        self.pgdn_btn = QtWidgets.QPushButton(self.change_page_gpbx)
        self.pgdn_btn.setGeometry(QtCore.QRect(154, 30, 71, 25))
        self.pgdn_btn.setObjectName("pgdn_btn")
        self.page_numb_label = QtWidgets.QLabel(self.change_page_gpbx)
        self.page_numb_label.setGeometry(QtCore.QRect(100, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.page_numb_label.setFont(font)
        self.page_numb_label.setObjectName("page_numb_label")
        self.audit_report_gpbx = QtWidgets.QGroupBox(self.centralwidget)
        self.audit_report_gpbx.setGeometry(QtCore.QRect(740, 290, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.audit_report_gpbx.setFont(font)
        self.audit_report_gpbx.setObjectName("audit_report_gpbx")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.audit_report_gpbx)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 211, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.audit_report_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.audit_report_btn.setObjectName("audit_report_btn")
        self.horizontalLayout_4.addWidget(self.audit_report_btn)
        self.submit_result_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.submit_result_btn.setObjectName("submit_result_btn")
        self.horizontalLayout_4.addWidget(self.submit_result_btn)
        Report_Checker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Report_Checker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 23))
        self.menubar.setObjectName("menubar")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        self.about_software_menu = QtWidgets.QMenu(self.menubar)
        self.about_software_menu.setObjectName("about_software_menu")
        Report_Checker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Report_Checker)
        self.statusbar.setObjectName("statusbar")
        Report_Checker.setStatusBar(self.statusbar)
        self.version_action = QtWidgets.QAction(Report_Checker)
        self.version_action.setObjectName("version_action")
        self.check_update_action = QtWidgets.QAction(Report_Checker)
        self.check_update_action.setObjectName("check_update_action")
        self.developer_action = QtWidgets.QAction(Report_Checker)
        self.developer_action.setObjectName("developer_action")
        self.gmail_action = QtWidgets.QAction(Report_Checker)
        self.gmail_action.setObjectName("gmail_action")
        self.about_software_menu.addAction(self.version_action)
        self.about_software_menu.addAction(self.check_update_action)
        self.about_software_menu.addSeparator()
        self.about_software_menu.addAction(self.developer_action)
        self.about_software_menu.addAction(self.gmail_action)
        self.menubar.addAction(self.help_menu.menuAction())
        self.menubar.addAction(self.about_software_menu.menuAction())

        self.retranslateUi(Report_Checker)
        QtCore.QMetaObject.connectSlotsByName(Report_Checker)

    def retranslateUi(self, Report_Checker):
        _translate = QtCore.QCoreApplication.translate
        Report_Checker.setWindowTitle(_translate("Report_Checker", "赋能起航报告审核工具"))
        self.get_date_gpbx.setTitle(_translate("Report_Checker", " 数据获取 "))
        self.load_report_list_btn.setText(_translate("Report_Checker", "载入报告列表"))
        self.clear_report_list_btn.setText(_translate("Report_Checker", "清空列表"))
        self.open_folder_gpbx.setTitle(_translate("Report_Checker", " 打开文件/文件夹 "))
        self.original_folder_btn.setText(_translate("Report_Checker", "原始报告库"))
        self.passed_folder_btn.setText(_translate("Report_Checker", "合格报告库"))
        self.open_ppt_btn.setText(_translate("Report_Checker", "打开当前原始报告"))
        self.download_gpbx.setTitle(_translate("Report_Checker", " 报告下载 "))
        self.download_selected_btn.setText(_translate("Report_Checker", "下载选中报告"))
        self.dwonload_page_btn.setText(_translate("Report_Checker", "下载当页报告"))
        self.download_all_btn.setText(_translate("Report_Checker", "下载所有未审核的报告"))
        self.change_page_gpbx.setTitle(_translate("Report_Checker", " 页面切换 "))
        self.pgup_btn.setText(_translate("Report_Checker", "上一页"))
        self.pgdn_btn.setText(_translate("Report_Checker", "下一页"))
        self.page_numb_label.setText(_translate("Report_Checker", "第 1 页"))
        self.audit_report_gpbx.setTitle(_translate("Report_Checker", " 报告审核 "))
        self.audit_report_btn.setText(_translate("Report_Checker", "审核报告"))
        self.submit_result_btn.setText(_translate("Report_Checker", "提交审核结果"))
        self.help_menu.setTitle(_translate("Report_Checker", "使用说明"))
        self.about_software_menu.setTitle(_translate("Report_Checker", "关于软件"))
        self.version_action.setText(_translate("Report_Checker", "版本：v 0.1"))
        self.check_update_action.setText(_translate("Report_Checker", "检查更新"))
        self.developer_action.setText(_translate("Report_Checker", "开发者：赵康明"))
        self.gmail_action.setText(_translate("Report_Checker", "zhaokm0@gmail.com"))

